FROM node:20

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm install --omit=dev

# Copy all source files
COPY . .

# Expose backend port
EXPOSE 4000

# Start Express server
CMD ["node", "server.js"]
