name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Navigate to project directory
          cd DEKHO-BHARAT
          
          # Pull the latest code
          git pull origin main
          
          # Navigate into the subfolder containing the docker-compose file
          cd "pep project"
          
          # Rebuild and restart the Docker containers
          sudo docker-compose down
          sudo docker-compose up --build -d
